language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '15'
git: 
  depth: 3
script:
  - yarn run build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "deploy release"
  on: 
    branch: render-with-clases
